// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:9e53f86a-8bd3-4645-956e-ed13569ccba0",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_aq1dWQbEb",
    "aws_user_pools_web_client_id": "7502ms3eck4ctpgl67iojsd1kl",
    "oauth": {}
};


export default awsmobile;
